interface PrintFooterProps {
  generatedBy?: string;
  pageNumber?: number;
}

/**
 * PrintFooter - one-line attribution that prints below the report
 * content. The official BMC seal stamp on every page is rendered
 * separately by PrintCornerStamp (fixed-positioned).
 */
export default function PrintFooter({ generatedBy }: PrintFooterProps) {
  return (
    <div className="print-only mt-8 pt-4 border-t border-bmc-900">
      <div className="flex items-center justify-between text-[9px] text-[var(--text-muted)]">
        <div className="flex items-center gap-2">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="/bmc_logo.png"
            alt=""
            aria-hidden="true"
            width={20}
            height={20}
            style={{ width: 20, height: 20, objectFit: 'contain' }}
          />
          <span>SWRMS · BMC Confidential · Pilot Deployment</span>
        </div>
        {generatedBy && <span>Generated by: {generatedBy}</span>}
        <span>© {new Date().getFullYear()} BMC · For official use only</span>
      </div>
    </div>
  );
}
