import BMCSeal from '@/components/brand/BMCSeal';

interface PrintFooterProps {
  generatedBy?: string;
  pageNumber?: number;
}

export default function PrintFooter({ generatedBy }: PrintFooterProps) {
  return (
    <div className="print-only mt-8 pt-4 border-t border-bmc-900">
      <div className="flex items-center justify-between text-[9px] text-[var(--text-muted)]">
        <div className="flex items-center gap-2">
          <BMCSeal size={20} variant="minimal" />
          <span>SWRMS · BMC Confidential · Pilot Deployment</span>
        </div>
        {generatedBy && <span>Generated by: {generatedBy}</span>}
        <span>© {new Date().getFullYear()} BMC · For official use only</span>
      </div>
    </div>
  );
}
