import type { Metadata } from 'next';
import PublicHeader from '@/components/layout/PublicHeader';
import PublicFooter from '@/components/layout/PublicFooter';
import { BMCHeritageBuilding } from '@/components/brand/Illustrations';

export const metadata: Metadata = { title: 'Privacy Policy' };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[var(--page-bg)]">
      <PublicHeader />

      <section className="relative bg-bmc-900 text-white py-12 sm:py-16 overflow-hidden">
        <div className="absolute right-0 top-0 bottom-0 w-2/3 max-w-2xl pointer-events-none text-bmc-600 opacity-25">
          <BMCHeritageBuilding className="w-full h-full" />
        </div>
        <div className="absolute inset-0 bg-gradient-to-r from-bmc-900 via-bmc-900/80 to-transparent pointer-events-none" />

        <div className="relative max-w-4xl mx-auto px-4 sm:px-6">
          <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-gold-300 mb-3">Legal</p>
          <h1 className="font-display text-3xl sm:text-4xl font-bold text-white">Privacy Policy</h1>
          <p className="text-sm text-white/70 mt-3">Effective date: April 2026 · Pilot Deployment</p>
        </div>
      </section>

      <section className="py-12 max-w-4xl mx-auto px-4 sm:px-6 w-full">
        <article className="bg-white border border-[var(--border)] rounded-xl shadow-doc p-8 sm:p-10 space-y-6 text-[14.5px] leading-relaxed text-[var(--text-secondary)]">
          <div>
            <h2 className="font-display text-lg font-bold text-bmc-700 mb-3">1. Scope</h2>
            <p>
              This Privacy Policy applies to the Smart Workforce &amp; Route Management System (SWRMS),
              a pilot deployment operated by the Brihanmumbai Municipal Corporation (BMC) Solid Waste
              Management Department for Chembur Ward.
            </p>
          </div>

          <div>
            <h2 className="font-display text-lg font-bold text-bmc-700 mb-3">2. Data we collect</h2>
            <ul className="space-y-2 list-disc list-inside marker:text-gold-600">
              <li><strong>Identity:</strong> Employee ID, name, role, ward assignment, contact phone.</li>
              <li><strong>Authentication:</strong> Password (stored as bcrypt hash, never in plain text).</li>
              <li><strong>Biometric (face embedding):</strong> 128-dimensional numeric vector derived from your enrollment photo, used for identity verification at field photo submissions.</li>
              <li><strong>Location at check-in:</strong> GPS coordinates captured at the moment of attendance check-in and at each photo submission.</li>
              <li>
                <strong>Live tracking during shift (opt-in):</strong> If you press <em>Start Shift Tracking</em> on your home screen,
                your device sends GPS samples every ~30 seconds while you are on the route. Tracking automatically stops
                when you press <em>Stop Tracking</em>, when you mark your route 100% complete, or when your shift end time passes.
                A pulsing green indicator and the words &ldquo;Tracking: ON&rdquo; are shown the entire time pings are flowing.
                Tracking is not silent and is never enabled without your explicit action.
              </li>
              <li><strong>Device metadata:</strong> User agent, platform string, and (on Android) the operating system&apos;s mock-location flag, for audit purposes.</li>
              <li><strong>Operational records:</strong> Attendance logs, route progress updates, geotagged photos, GPS pings during opted-in tracking.</li>
            </ul>
          </div>

          <div>
            <h2 className="font-display text-lg font-bold text-bmc-700 mb-3">3. How we use it</h2>
            <p>
              All data is used solely for verifying field staff presence at assigned routes, monitoring
              waste collection completion, detecting route deviations and idle periods during shift, and
              supporting workforce reallocation decisions by authorized supervisors. Data is not sold,
              rented, or shared with third parties.
            </p>
            <p className="mt-3">
              GPS pings collected during live tracking are used in two ways: (a) to power the supervisor&apos;s
              real-time map showing which workers are on/off route, and (b) to run automatic deviation
              and idle detection. Alerts generated by these checks are reviewed by your supervisor and
              recorded in the verification log.
            </p>
          </div>

          <div>
            <h2 className="font-display text-lg font-bold text-bmc-700 mb-3">4. Who can access your data</h2>
            <ul className="space-y-2 list-disc list-inside marker:text-gold-600">
              <li>You (your own attendance, photos, and route data via your account).</li>
              <li>Your assigned supervisor (your attendance, photos, and verification flags for your route).</li>
              <li>BMC SWM administrators (aggregate data and verification logs across all wards in pilot scope).</li>
            </ul>
          </div>

          <div>
            <h2 className="font-display text-lg font-bold text-bmc-700 mb-3">5. Data retention</h2>
            <p>
              Operational data (attendance, photos, logs) is retained for 365 days for audit purposes,
              after which it is archived or deleted per BMC records policy. Face embeddings are retained
              for the duration of your active employment in SWRMS.
            </p>
            <p className="mt-3">
              GPS pings from live tracking are retained for 90 days for incident investigation and
              GPS-replay reviews, then deleted. Aggregated anonymous statistics (e.g. average shift
              completion percentage per ward) may be retained indefinitely.
            </p>
          </div>

          <div>
            <h2 className="font-display text-lg font-bold text-bmc-700 mb-3">6. Security</h2>
            <p>
              Passwords are hashed using bcrypt. Sessions use signed JWT tokens with 24-hour expiry.
              All API calls are protected by role-based access control. The system runs on encrypted
              MongoDB Atlas infrastructure.
            </p>
          </div>

          <div>
            <h2 className="font-display text-lg font-bold text-bmc-700 mb-3">7. Your rights</h2>
            <p>
              Under applicable Indian data protection regulations including the Digital Personal Data
              Protection Act 2023, you have the right to access, correct, or request deletion of your
              personal data. Contact the M-East Ward SWM Office to exercise these rights.
            </p>
          </div>

          <div>
            <h2 className="font-display text-lg font-bold text-bmc-700 mb-3">8. Contact</h2>
            <address className="not-italic">
              Data Protection Officer<br />
              M-East Ward Office, BMC SWM Department<br />
              19B, 20A, Rd No. 1, Chembur Gaothan, Mumbai 400 071<br />
              Helpdesk: 1916
            </address>
          </div>
        </article>
      </section>

      <PublicFooter />
    </div>
  );
}
